server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shirotest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:                          # ”ÕºΩ‚Œˆ∆˜
    view:
      suffix: .ftl
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl